#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinDemo.Resource", IsApplication=true)]

namespace XamarinDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bullet = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int d_pad = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int exit_button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int fire_button = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int fuel_bar = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int fuel_pointer = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int game_bg = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int game_bg1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int game_bg_left = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int game_bg_right = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int heli2_l = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int heli2_r = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int heli_l = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int heli_r = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int jet_l = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int jet_r = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int menu_bg = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int play = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int player_explosion = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int player_left = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int player_middle = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int player_right = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ship_l = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ship_r = 2130837527;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
